name: stemcell
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  fluttery: 0.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - graphics/amusements.jpg
  - graphics/seesaw.jpg
  - graphics/sittingdog.png
  - graphics/Gym.jpg
  - graphics/WoodenBackground.jpg
  - graphics/grunge.jpg
  - graphics/ferrari.jpg
  - graphics/Lego_1.jpg
  - graphics/images.png
  - graphics/benchpress.jpg
  - graphics/HorizontalBar.jpg
  - graphics/transport.jpeg
  - graphics/roadroller.jpg
  - graphics/steamengine.jpg
  - graphics/aircraft.jpg
  - graphics/ATV.jpg
  - graphics/dumbbell.png
  - graphics/parallel.png
  - graphics/wildhorse.png
  - graphics/stretcher.png
  - graphics/machine.jpg
  - graphics/IndustrialGrinder.png
  - graphics/Hammer.png
  - graphics/WheelChair.jpg
  - graphics/HospitalBed.jpg
  - graphics/catapult.png
  - graphics/ladder.png
  - graphics/flour.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Bebas-neue
       fonts:
         - asset: fonts/BebasNeue-Regular.ttf
     - family: HelveticaNeue
       fonts:
         - asset: fonts/HelveticaNeue.ttf
     - family: Mermaid
       fonts:
         - asset: fonts/Mermaid.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
